plugins {
    id 'java'
    id 'io.qameta.allure' version '2.11.2'  // или актуальная версия
}
allure {
    adapter {
        aspectjWeaver.set(true)
        frameworks {
            junit5 {
                adapterVersion.set("2.23.0")
            }
        }
    }
    report {
        version.set("2.23.0")
    }
}
repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform("org.junit:junit-bom:5.14.2")
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.junit.jupiter:junit-jupiter-params'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'commons-io:commons-io:2.15.0'
    testImplementation 'com.codeborne:pdf-test:1.5.0'
    testImplementation 'com.codeborne:xls-test:1.4.3'
    testImplementation 'com.opencsv:opencsv:5.9'
    testImplementation 'com.google.code.gson:gson:2.10.1'
    testImplementation 'com.codeborne:selenide:7.14.0'
    testImplementation 'net.datafaker:datafaker:2.5.4'
    testImplementation 'org.assertj:assertj-core:3.25.3'
    testImplementation 'org.aeonbits.owner:owner:1.0.12'


    // Allure зависимости
    testImplementation 'io.qameta.allure:allure-selenide:2.23.0'
    testImplementation 'io.qameta.allure:allure-junit5:2.23.0'
    testImplementation 'org.aspectj:aspectjweaver:1.9.21'
}

test {
    useJUnitPlatform()
    systemProperties(System.getProperties()) //вынос параметров
    systemProperty 'allure.results.directory', file('build/allure-results')
    jvmArgs = [
            "-javaagent:${configurations.testRuntimeClasspath.find { it.name.contains('aspectjweaver') }.absolutePath}"
    ]
    testLogging {
        events "passed", "skipped", "failed"
        showStandardStreams = true
    }
}












